# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Y4gYesyvHQ6VW3wtV84wqwzdndJziVf
"""

import tensorflow_datasets as tfds
from

import pandas as pd
import numpy as np
df = pd.DataFrame(CV_data.take(50), columns=CV_data.columns)
base_datos = pd.to_csv("drive/MyDrive/archive.zip")
base_datos = pd.read_csv("drive/MyDrive/face_detection.json")

#esto es pandas
lista_trainig = base_datos["Usage"]=="Training"
lista_test = base_datos["Usage"]!="Training"

Datos_train = base_datos.loc[lista_trainig]
Datos_test =base_datos.loc[lista_test]
X_train1 = Datos_train["pixels"]
Y_train1 = Datos_train["emotion"]

#esto es numpy
X_train = np.array(X_train1)
Y_train = np.array(Y_train1)
print(X_train.shape)

import tensorflow as tf
Y_train= tf.keras.utils.to_categorical(Y_train, num_classes=7)

x = np.zeros((22872,48,48,1))


for y in range (22872):
  x[y,:,:,0] = np.reshape(list(map(int, X_train[y].split(" "))), (48, 48))
  print(y)

from matplotlib import pyplot as plt
plt.imshow(x[2,:,:,0])
np.max(x[2,:,:,0])
print(x.shape)

import tensorflow.keras
import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.ZeroPadding2D((1,1),input_shape=(48,48,1)))
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPool2D((2,2), strides=(2,2),padding='same'))

model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(128, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(128, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPool2D((2,2), strides=(2,2),padding='same'))

model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(256, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(256, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(256, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPool2D((2,2), strides=(2,2),padding='same'))

model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu'))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
model.add(tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPool2D((2,2), strides=(2,2),padding='same'))

model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(1024, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(1024, (3, 3), activation='relu'))
model.add(tf.keras.layers.ZeroPadding2D((1,1)))
model.add(tf.keras.layers.Conv2D(1024, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPool2D((2,2), strides=(2,2),padding='same'))

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(4096, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(4096, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(7, activation='softmax'))

print(x.shape)
print(Y_train.shape)

model.compile(optimizer="Adam", loss="categorical_crossentropy", metrics=["accuracy"])
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath='./drive/MyDrive/resultados_CNN_Python/Resultados.h5',
    save_weights_only=False,
    monitor='val_accuracy',
    mode='max',
    save_best_only=True)
model.fit(x=x, y=Y_train, batch_size=32, epochs=70, validation_split=0.3, callbacks=[model_checkpoint_callback])